### ISSUE TITLE
Some titles are not found in worldcat: multi-part novels

### ISSUE THREAD

**Issue by christofs** [distantreading/worldcat#6]
We need to think of a solution for multi-part novels, where the combined title is not found in Worldcat, but both the series title and the individual titles may be found. 

An example is the title "Jean-Christophe, tome 5: La foire sur place". Either we search for "Jean-Christophe" (but then may get too many editions), or for "La foire sur place" (and then may get too few editions). 

In my opinion, the solution needs to lie in the "title" element of the XML files. It should be possible for our script to pick either the series title or the individual title, to find editions.

**Comment by lb42** [comment]
I am not sure what the "bug" is here. The <title> element has a @level attribute which could be used to distinguish different kinds of title  (series, monograph, etc.) but we excluded it from the schema along with lots of other bibliographic arcana on the grounds that we are not aiming to duplicate the efforts of librarians. The title we supply in our title statement is the ELTeC simple minded title, and we provide a link elsewhere for those curious as to what it corresponds with. If we then base a bibliographic search on the contents of the ELTeC smt, we must expect to have to tweak the results (or the search strings). In fact my experiments with the current  titles in  both the English and the French collections suggest that some tweaking is essential. For example, just using the current French titles "as is" resulted in a dozen titles with no occurrences at all in the BNF catalogue -- mostly because of spelling errors.

**Comment by CarolinOdebrecht** [comment]
I think, the title element informs about the TEI ELTeC document which represents a novel being in the ELTeC Edition. We might assume that the strings in titles element might be phrased in different ways, including series titles/parts of series titles, short titles etc. As you have pointed out, this will make things difficult when we automatically search or novels in world cat.

In order to have a consistent location for this information for all types of documents and language collection we could think about using the bibl-structure.
If we use attributes in the titleStmt: We need controled vocabularies: a title for the TEI ELTeC document, a title for the novel, a title for series.

**Comment by christofs** [comment]
Assuming we want to avoid any further meddling with the teiHeader's data model, and further assuming that some issues with the title as it is stated in the titleStmt will always occur (and although it is important to learn there are spelling errors that could be fixed), I think we need to offer a systematic way of allowing for some tweaking of the title to enable worldcat to return reprints. 

My idea would be to implement the following feature: 

1. With the title given in the teiHeader, the script looks for reprints in worldcat. 
2. If the number of reprints is not zero (or not higher than n), proceed as usual 
3. If the number of reprints is zero (or below n), provide the title as used to the user and allow the user to input an alternative form of the title; then repeat the query process 
4. If an alternative form of the title was used for data ultimately saved in the reprint counts table, that alternative form should be documented somewhere. At the very least, in the log files.

**Comment by lb42** [comment]
Clearly, if we find no hits for the string in the ELTeC title field, the title field needs to be corrected! (I am thinking for example of G. Flaubert's famous non-existent novel "Sallambo")

I find it much easier for a slightly complicated but inherently error-prone procedure like this to run a batch script, which can be tuned as often as needed to get it right. If that script is stored in the repo, then we can always check on what needed changing.  The procedure you are describing assumes that "no hits" is the only thing that can go wrong: "too many hits" is also a possibility which might require modifying the search beyond simply  substring-before(teiHeader/titleStmt/title,': ELTeC') (e.g. to make sure we get only "swann's way" and not all of ALRDTP) 

Since the number of titles to be searched for is not that big (a maximum of 100 at a time, I assume), it's not much of an overhead to run a series of batch commands, each corresponding with one of the following steps:
1. extract search strings from TEI Headers
2. run search strings and save resulting records (USMARC or Unimarc, in my case; HTML screen dumps in yours)
3. Are the results plausible? If not, tweak the search strings as required and go back to 2.
4 Process retrieved results to extract the useful data [details forthcoming!]

**Comment by christofs** [comment]
I agree that if there is a spelling error (Sallambo), it needs to be fixed. But that's an issue entirely different from a useful and correct title that still does not yield any results (title that has more information or is more specific than what WorldCat expects). And it is yet another case when a query yields too many results (title that is too general to yield adequat results). 

It seems to me we have several options: 

(1) We adjust our titles to match worldcat expectations, so to speak. If we remove useful information such as the series title from the "titleStmt/title" element, we should add it elsewhere. After all, it is important information that "Du côté de chez Swann" is part of "À la recherche du temps perdu" even when "À la recherche du temps perdu, part/book/volume 1: Du côté de chez Swann" does not yield any hits in worldcat.  
(2) We introduce a clear, machine-readable convention on how to deal with series titles and novel titles, so that we can automatically chose the novel title rather than the series title. There might be more cases to consider. This may get complex quite quickly as we have ten or more national traditions. And it makes our header more complicated.  
(3) We deal with such errors at run-time, for example by providing the option to adjust the title string that is used to search in worldcat while leaving the title contained in the titleStmt unchanged. 

I thought option 3 was elegant, because it does not constrain what goes into "titleStmt/title" based on requirements coming from searching a library cataolgue, and provides some flexibility. The downside I see is that it makes the process less transparent and that it doesn't "just run". I could live with option 1 if we have a good place for the series title information somewhere in the header. If it was my own little project I'd implement option 2 and tell my script to look only into the "title" element with @type="main".

**Comment by christofs** [comment]
Solved for now by having only the main title in the "title" element.
